version: "v2.29.2-desktop.2"
services:

  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev